name: CI/CD Taller MLOps No 2

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read
  issues: write
  pull-requests: write
  packages: write

jobs:
  pruebas-unitarias:
    name: Ejecutar pruebas unitarias
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Comentar inicio del pipeline en el PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "CI/CD en acción. Ejecutando tareas …"
            })

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar pruebas unitarias
        run: pytest tests/test_modelo.py -v

      - name: Comentar finalizacion exitosa en el PR
        if: github.event_name == 'pull_request' && success()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "CI/CD terminado con éxito."
            })

  construir-y-publicar-imagen:
    name: Construir y publicar imagen Docker
    runs-on: ubuntu-latest
    needs: pruebas-unitarias

    if: github.event_name == 'push'

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Convertir nombre de imagen a minusculas
        run: |
          echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Autenticarse en GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generar metadata de imagen Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Construir y publicar imagen Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}